# This file was generated by GoReleaser. DO NOT EDIT.
cask "orla" do
  name "orla"
  desc "A dead-simple unix tool for lightweight agents"
  homepage "https://github.com/dorcha-inc/orla"
  version "0.0.0-test-20260107-035739"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orla"

  on_macos do
    on_intel do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-darwin-amd64.tar.gz"
      sha256 "604f666abfbd0bb22dc89826aaaac59f200d16fb27fda7e8fca7ec9690b0563c"
    end
    on_arm do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-darwin-arm64.tar.gz"
      sha256 "a3c722ed1b5afdc8d8ca3701428922133ac432d0df20d9047e6d05df81a7710e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-linux-amd64.tar.gz"
      sha256 "8b278f5001beeb3b4cec357c125aa4fd4eda9f40c9250b57d82b0afae80a26e4"
    end
    on_arm do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-linux-arm64.tar.gz"
      sha256 "448f77be87686839262619cb345bf6ff273e128203cdd55e6bde87d0a5f44eeb"
    end
  end

  postflight do
    skip_ollama = ENV["HOMEBREW_ORLA_SKIP_OLLAMA"] == "1"
    if skip_ollama
      system "/bin/sh", "-c", "export PATH=\"/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:$PATH\" && curl -fsSL https://raw.githubusercontent.com/dorcha-inc/orla/main/scripts/install.sh | sh -s -- --homebrew --skip-ollama"
    else
      system "/bin/sh", "-c", "export PATH=\"/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:$PATH\" && curl -fsSL https://raw.githubusercontent.com/dorcha-inc/orla/main/scripts/install.sh | sh -s -- --homebrew"
    end
  end

  # No zap stanza required
end
