# This file was generated by GoReleaser. DO NOT EDIT.
cask "orla" do
  name "orla"
  desc "A dead-simple unix tool for lightweight agents"
  homepage "https://github.com/dorcha-inc/orla"
  version "0.0.0-test-20260107-025816"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orla"

  on_macos do
    on_intel do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-darwin-amd64.tar.gz"
      sha256 "0ea7824dc3b26e34e08031e2d4e3313bc572924491809277b67a5fc4b59cffd1"
    end
    on_arm do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-darwin-arm64.tar.gz"
      sha256 "1ea36c3be338137cda700ab08ae9a2c0acd6b87c239cc4276b44ecef305ff889"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-linux-amd64.tar.gz"
      sha256 "63878fdae83613700dee3bfa76a91f26ec78558d57274fa0bc289e92d1b63e1b"
    end
    on_arm do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-linux-arm64.tar.gz"
      sha256 "ea87d27d50a34b47a8b22f7742f5f4ce5574ca6a85aa42c6edf269e30b0d059b"
    end
  end

  postflight do
    system "/bin/sh", "-c", "export PATH=\"/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:$PATH\" && if [ \"$ORLA_SKIP_OLLAMA\" = \"1\" ]; then curl -fsSL https://raw.githubusercontent.com/dorcha-inc/orla/main/scripts/install.sh | sh -s -- --homebrew --skip-ollama; else curl -fsSL https://raw.githubusercontent.com/dorcha-inc/orla/main/scripts/install.sh | sh -s -- --homebrew; fi"
  end

  # No zap stanza required
end
